apiVersion: v1
kind: Pod
metadata:
  name: go-app-crash
  labels:
    app: go-app
spec:
  containers:
  - name: go-app
    image: ghcr.io/heartinice/containers-lab-1/app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    env:
      - name: DB_HOST
        value: "postgres-service"
